#ifndef PLUGIN_EVENTS
#define PLUGIN_EVENTS

#ifdef __cplusplus
extern "C" {
#endif

/* Types */
enum {
	PLUGIN_EVENT_TYPE_HOTKEY = 1
};

/* Hotkey subtypes */
enum {
	/* Toggle */
	PLUGIN_EVENT_SUBTYPE_HOTKEY_TOGGLE_MICRO_ON = 1,
	PLUGIN_EVENT_SUBTYPE_HOTKEY_TOGGLE_MICRO_OFF,
	PLUGIN_EVENT_SUBTYPE_HOTKEY_TOGGLE_MUTE_MICRO_ON,
	PLUGIN_EVENT_SUBTYPE_HOTKEY_TOGGLE_MUTE_MICRO_OFF,

	PLUGIN_EVENT_SUBTYPE_HOTKEY_TOGGLE_SPEAKER_ON,
	PLUGIN_EVENT_SUBTYPE_HOTKEY_TOGGLE_SPEAKER_OFF,
	PLUGIN_EVENT_SUBTYPE_HOTKEY_TOGGLE_AWAY_ON,  /* Away message, if available, in message string */
	PLUGIN_EVENT_SUBTYPE_HOTKEY_TOGGLE_AWAY_OFF,

	/* Activate */
	PLUGIN_EVENT_SUBTYPE_HOTKEY_ACTIVATE_MICRO,
	PLUGIN_EVENT_SUBTYPE_HOTKEY_ACTIVATE_MUTE_MICRO,
	PLUGIN_EVENT_SUBTYPE_HOTKEY_ACTIVATE_SPEAKER,
	PLUGIN_EVENT_SUBTYPE_HOTKEY_ACTIVATE_AWAY,  /* Away message, if available, in message string */

	/* Deactivate */
	PLUGIN_EVENT_SUBTYPE_HOTKEY_DEACTIVATE_MICRO,
	PLUGIN_EVENT_SUBTYPE_HOTKEY_DEACTIVATE_MUTE_MICRO,
	PLUGIN_EVENT_SUBTYPE_HOTKEY_DEACTIVATE_SPEAKER,
	PLUGIN_EVENT_SUBTYPE_HOTKEY_DEACTIVATE_AWAY
};


#ifdef __cplusplus
}
#endif

#endif
